var chinese = {
    maintitle: "全景摄像机管理系统",
    video: "视频",
    nvr: "网络硬盘录像机",
    camera: "摄像机",
    device: "设备",
    information: "信息",
    system: "系统",
    panoramic: "全景摄像机",
    time: "时间",
    power: "电源",
    version: "版本",
    server: "服务",
    service: "服务器",
    search: "搜索",
    error: "错误",
    number: "号码",
    home: "主页",
    preview: "预览",
    playback: "回放",
    and: "与",
    id: "编号",
    none: "无",
    serialnumber: "序列号",
    name: "名称",
    model: "型号",
    firmware: "固件",
    released: "发布",
    date: "日期",
    year: "年",
    month: "月",
    day: "日",
    hardware: "硬件",
    description: "描述信息",
    connection: "连接",
    usage: "使用率",
    check: "检测",
    to: "到",
    ge: "个",
    view: "显示",
    output: "输出",
    memory: "内存",
    hour: "小时",
    minute: "分钟",
    second: "秒",
    online: "在线",
    offline: "离线",
    start: "开始",
    stop: "停止",
    choose: "选择",
    allselected: "全选",
    inverseselected: "反选",
    cancel: "取消",
    yet: "已",
    save: "保存",
    database: "数据库",
    over: "完毕",
    ok: "确定",
    delete_prompt: "是否确定删除选中",
    "delete": "删除",
    success: "成功",
    activation: "激活",
    create: "创建",
    expired: "过期",
    upload: "上传",
    "return": "返回",
    file: "文件",
    again: "重新",
    remove: "移除",
    your: "您的",
    already: "已经",
    modify: "修改",
    basic: "基本",
    group: "组",
    coordinate: "坐标",
    text: "文字",
    font: "字体",
    size: "大小",
    color: "颜色",
    screen: "屏幕",
    buildin: "内置",
    edit: "编辑",
    manufacturer: "厂商",
    pointofsale: "零售商",
    uri: "访问地址",
    protocol: "协议",
    type: "类型",
    username: "用户名",
    password: "密码",
    run: "运行",
    auto: "自动",
    login: "登录",
    manager: "管理员",
    encoder: "编码器",
    decoder: "解码器",
    gpu: "图形处理器",
    setting: "设置",
    list: "列表",
    manage: "管理",
    close: "关闭",
    failed: "失败",
    login_failed: "用户名或密码错误",
    display: "显示",
    sunday: "星期日",
    monday: "星期一",
    tuesday: "星期二",
    wednesday: "星期三",
    thursday: "星期四",
    friday: "星期五",
    saturday: "星期六",
    address: "地址",
    advanced: "高级",
    config: "配置",
    more: "更多",
    connected: "已连接",
    disconnected: "未连接",
    other: "其他",
    reboot: "重启",
    "default": "默认",
    gateway: "网关",
    primary: "首选",
    secondary: "备用",
    subnet: "子网",
    mask: "掩码",
    network: "网络",
    get: "获取",
    "static": "静态",
    dynamic: "动态",
    data: "数据",
    pdc: "客流",
    census: "统计",
    journaling: "报表",
    contrast: "对比",
    only: "只",
    unsaved: "未保存",
    useIPAsTheNameWhenAdding: "IP作为名称保存",
    add: "添加",
    yes: "是",
    no: "否",
    sync: "同步",
    enable: "启用",
    lastNSeconds: "最近N秒人数",
    not: "未",
    bind: "绑定",
    help: "帮助",
    face: "人脸",
    recognition: "识别",
    realtime: "实时",
    monitor: "监控",
    snap: "抓拍",
    alarm: "报警",
    main: '主',
    version_no: "版本号",
    deed: '作为',
    please_choose: '请选择',
    view_video_file: '查看录像文件',
    searching: "搜索中",
    operation: '操作',
    is_true_restart_camera: '是否确定重启摄像机',
    is_true_restart_nvr: '是否确定重启网络硬盘录像机',
    is_true_restart_encoder: '是否确定重启编码器',
    is_true_del_channel_dev: '是否确定删除该通道设备',
    is_true_rebinding: '该摄像机已绑定了，是否重新绑定',
    is_true_close_computer: '是否确定关机',
    is_true_restart_computer: '是否确定重启',
    is_true_resete_computer: '是否确定恢复出厂设置',
    associated_decoding_unit: '已关联解码单元',
    format_wrong: "格式不对",
    switch: '切换',
    encoding_channel: '编码通道',
    synchronous: '同步',
    system_control: '系统控制',
    time_zone: '时区',
    host_name: '主机名',
    timing: '校时',
    interval: '间隔',
    local: '本地',
    shut_down: '关机',
    restart_computer: '重启',
    resete_computer: '出厂设置',
    not_trim: '不能为空',
    next_step: '下一步',
    prev_setp: '上一步',
    finish: ' 完成',
    angle: '角度',
    all: '全部',
    loading: '加载中',
    binding: '配置',
    unbinding: '未配置',
    relation: "关系",
    event: "事件",
    record: "记录",
    fore_end: "前端",
    back_end: "后端",
    similar: "相似度",
    touch_off: "触发",
    threshold: "阈值",
    capacity: "容量",
    max: "最大",
    value: "值",
    high: "高",
    middle: "中",
    low: "低",
    blacklist: "黑名单",
    whitelist: "白名单",
    priority: "优先级",
    face_database: "人脸库",
    sex: "性别",
    full_name: "姓名",
    phone: "电话号码",
    birthday: "生日",
    province: "省份",
    city: "城市",
    card_type: "证件类型",
    card_number: "证件编号",
    employee_id: "员工ID",
    extend: "附加信息",
    prompt: "提示",
    query: "查询",
    comparison: "比对",
    library: "库",
    result: "结果",
    condition: "条件",
    end: "结束",
    unlimited: "不限",
    secrecy: "保密",
    is_true_eye_glass: "是否戴眼镜",
    channel: "通道",
    whether: "是否",
    mode: "模式",
    centre: "中心",
    pulse: "脉冲",
    continued: "持续",
    worksheet: "工作表",
    associate: "关联",
    linkage: "联动",
    empty: "清空",
    according: "按",
    picture: "图片",
    copy:"复制",
    use:"使用",
    the:"的",
    sunday:"星期日",
    monday:"星期一",
    tuesday:"星期二",
    wednesday:"星期三",
    thursday:"星期四",
    friday:"星期五",
    saturday:"星期六",
    batch:"批量",
    please:"请",
    correct:"正确",
    input:"输入"
}

class LanguagePackage {
    constructor() {
        this.key = 'chinese';
        this.chinese = chinese;
    }
}

var english = {}

function init_language() {
    var AttrLangType = {
        "title-language": "title",
        placeholder: "placeholder"
    }
    var lang = "";
    for (var key in AttrLangType) {
        $("[" + key + "]").attr(AttrLangType[key], function () {
            try {
                lang = this.getAttribute(key);
                if (lang) return chinese[lang] ? chinese[lang] : lang;
            }
            finally {
                this.removeAttribute(key);
            }
        });
    }
    $("[language]").html(function () {
        try {
            lang = this.getAttribute("language");
            if (lang) return chinese[lang] ? chinese[lang] : lang;
        }
        finally {
            this.removeAttribute("language");
        }
    });
}